### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by Vyryn** [ExterraGroup/pyrsi#1]
* Python RSI version: 0.1.8
* Python version:  3.7.4 
* Operating System: Windows 10 build 18362

### Description

I was attempting to install pyrsi with pip.
Expected result: Package installed successfully.
Actual result: ERROR

### What I Did

1) From JetBeans terminal, pip install pyrsi
2) open powershell, pip install pyrsi

Response with error below.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Vyryn> pip install pyrsi
Collecting pyrsi
  Using cached https://files.pythonhosted.org/packages/90/df/3cfb9a4cfec890efef2768e2364e77733250b885f8c6adc3ce087aa57ba8/pyrsi-0.1.8-py2.py3-none-any.whl
Collecting fuzzywuzzy==0.17.0
  Using cached https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl
Collecting wptools==0.4.17
  Using cached https://files.pythonhosted.org/packages/e2/5c/0d8af5532e44477edeb3dac81d3a611ea75827a18b6b4068c3cc2188bfe5/wptools-0.4.17-py2.py3-none-any.whl
Collecting python-Levenshtein==0.12.0
  Using cached https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz
Collecting requests==2.20.1
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting cachetools==2.1.0
  Using cached https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Collecting lxml
  Downloading https://files.pythonhosted.org/packages/24/c2/560d8561fd8260e258045aa3f74af39e07614a1cb9a816418328a016b658/lxml-4.4.2-cp37-cp37m-win32.whl (3.3MB)
     |████████████████████████████████| 3.3MB 1.3MB/s
Collecting html2text
  Using cached https://files.pythonhosted.org/packages/49/21/eb38d335ab15fc13564a5e971c1403707fb3a037292f246fa82e17208794/html2text-2019.9.26-py3-none-any.whl
Collecting pycurl
  Using cached https://files.pythonhosted.org/packages/ac/b3/0f3979633b7890bab6098d84c84467030b807a1e2b31f5d30103af5a71ca/pycurl-7.43.0.3.tar.gz
    ERROR: Command errored out with exit status 10:
     command: 'c:\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Vyryn\\AppData\\Local\\Temp\\pip-install-zlrzogik\\pycurl\\setup.py'"'"'; __file__='"'"'C:\\Users\\Vyryn\\AppData\\Local\\Temp\\pip-install-zlrzogik\\pycurl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Vyryn\AppData\Local\Temp\pip-install-zlrzogik\pycurl\pip-egg-info'
         cwd: C:\Users\Vyryn\AppData\Local\Temp\pip-install-zlrzogik\pycurl\
    Complete output (1 lines):
    Please specify --curl-dir=/path/to/built/libcurl
    ----------------------------------------
ERROR: Command errored out with exit status 10: python setup.py egg_info Check the logs for full command output.

**Comment by ventorvar** [comment]
Closed by cd69fc6. Removed a dependency that wasn't being used that was failing to install on Windows.  The newest version of 0.1.10 should work for ya. Thanks!
